name: Build, Lint and Test package
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:

      - name: Copy repository
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build
